<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array>
    <string>svi</string>
   </array>
  <key>name</key>
  <string>svi</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.svi</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>((\$l|\$s):[a-zA-Z0-9_]*)</string>
          <key>name</key>
          <string>variable.svi</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((o|p):[a-zA-Z0-9_]*)</string>
          <key>name</key>
          <string>entity.name.type.svi</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(f:[a-zA-Z0-9_]*)</string>
          <key>name</key>
          <string>entity.name.function.svi</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&lt;\-)</string>
          <key>name</key>
          <string>punctuation.svi</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(true|false)</string>
          <key>name</key>
          <string>keyword.svi</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(beginfn|fnparam|return|curry|callif|callelse|call|pushcallif|pushcallelse|pushcall|drain|exit|out|err|streaminit|streampush|streampop|streamclose|streamempty|typify|lock|unlock|equal|scopeof|typeof|compatible|nand|and|xor|nor|or|not|mapinit|mapset|mapget|maplength|mapkeys|enuminit|enumappend|enumprepend|enumlength|enumget|enumset|enumerate|strconcat|strlength|strslice|plus|minus|times|divide|power|mod|neg|gte|gt|lte|lt|while|with|pushexhandler|popexhandler|raise|resume|otypeinit|otypeprop|otypedel|otypeget|otypefinalize|otypesubset|objinit|objset|objget|objinstance|objcurry)</string>
          <key>name</key>
          <string>keyword.svi</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.svi</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.svi</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.svi</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\-\-.*)</string>
          <key>name</key>
          <string>comment.svi</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\b\d+\.\d+)</string>
          <key>name</key>
          <string>constant.numeric.svi</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.svi</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
