# The executable to write
TARGET_EXEC ?= swarmc

# Some helper constants
BUILD_DIR ?= ./build
DEBUG_BUILD_DIR ?= ./build_debug
SRC_DIRS ?= ./src
LEXER := flex
BISON := bison
Q := @
CXX := clang++
ECHO := $(Q)./bin/color.bash
ECXX := $(ECHO) blue "    CXX "
ELEXER := $(ECHO) yellow "  LEXER "
EPARSER := $(ECHO) purple " PARSER"
EBIN := $(ECHO) green "    BIN "

# Files automatically generated by Bison. Removed by clean.
BISON_FILES := src/bison/grammar.hh src/bison/parser.cc src/bison/parser.output src/bison/stack.hh src/bison/parser_debug.cc src/bison/parser_debug.output

SRCS := $(shell find $(SRC_DIRS) -name *.cpp -or -name *.c -or -name *.s)
HEADERS := $(shell find $(SRC_DIRS) -name *.hpp -or -name *.h)
OBJS := $(SRCS:%=$(BUILD_DIR)/%.o)
DEPS := $(OBJS:.o=.d)
DEBUG_OBJS := $(SRCS:%=$(DEBUG_BUILD_DIR)/%.o)
DEBUG_DEPS := $(DEBUG_OBJS:.o=.d)

INC_DIRS := $(shell find $(SRC_DIRS) -type d)
INC_FLAGS := $(addprefix -I,$(INC_DIRS))

CXXFLAGS += -std=c++20
CPPFLAGS ?= $(INC_FLAGS) -MMD -MP -g -std=c++20 -Wall
CPPFLAGS_debug ?= $(INC_FLAGS) -MMD -MP -g -std=c++20 -Wall -DSWARM_DEBUG #-DNSLIB_GC_TRACK
#LDFLAGS ?= -lredis++ -lhiredis -pthread
LDFLAGS ?= -rdynamic -ldl -lbinn -pthread

$(TARGET_EXEC): $(OBJS) $(HEADERS) $(BUILD_DIR)/parser.o $(BUILD_DIR)/lexer.o
	$(EBIN) $@
	$(Q)$(CXX) $(OBJS) $(BUILD_DIR)/parser.o $(BUILD_DIR)/lexer.o -o $@ $(LDFLAGS)

.PHONY: all
all: $(TARGET_EXEC) debug

# c++ sources
$(BUILD_DIR)/%.cpp.o: %.cpp %.h src/bison/parser.cc
	$(Q)$(MKDIR_P) $(dir $@)
	$(ECXX) $<
	$(Q)$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $< -o $@

# Build the flex-generated lexer source. Relies on parser code, so build that first.
$(BUILD_DIR)/lexer.yy.cc: src/swarm.l $(BUILD_DIR)/parser.o
	$(ELEXER) $<
	$(Q)$(LEXER) --outfile $(BUILD_DIR)/lexer.yy.cc $<

$(BUILD_DIR)/lexer.o: $(BUILD_DIR)/lexer.yy.cc
	$(ECXX) $<
	$(Q)$(CXX) $(CPPFLAGS) -c $(BUILD_DIR)/lexer.yy.cc -o $(BUILD_DIR)/lexer.o

$(BUILD_DIR)/parser.o: src/bison/parser.cc
	$(ECXX) $<
	$(Q)$(CXX) $(CPPFLAGS) -c -o $@ $<



# Build a version with debugging enabled. Should be (mostly) non-clashing with the release version
debug: $(DEBUG_OBJS) $(HEADERS) $(DEBUG_BUILD_DIR)/parser_debug.o $(DEBUG_BUILD_DIR)/lexer.o
	$(EBIN) $(TARGET_EXEC)_debug
	$(Q)$(CXX) $(DEBUG_OBJS) $(DEBUG_BUILD_DIR)/lexer.o $(DEBUG_BUILD_DIR)/parser_debug.o -o $(TARGET_EXEC)_debug $(LDFLAGS) $(CPPFLAGS_debug)

# c++ sources for debug
$(DEBUG_BUILD_DIR)/%.cpp.o: %.cpp %.h src/bison/parser_debug.cc
	$(Q)$(MKDIR_P) $(dir $@)
	$(ECXX) $<
	$(Q)$(CXX) $(CPPFLAGS_debug) $(CPPFLAGS_debug) -c $< -o $@

# Build the flex-generated lexer source. Relies on parser code, so build that first.
$(DEBUG_BUILD_DIR)/lexer.yy.cc: src/swarm.l $(DEBUG_BUILD_DIR)/parser_debug.o
	$(ELEXER) $<
	$(Q)$(LEXER) --outfile $(DEBUG_BUILD_DIR)/lexer.yy.cc $<

$(DEBUG_BUILD_DIR)/lexer.o: $(DEBUG_BUILD_DIR)/lexer.yy.cc
	$(ECXX) $<
	$(Q)$(CXX) $(CPPFLAGS_debug) -c $(DEBUG_BUILD_DIR)/lexer.yy.cc -o $(DEBUG_BUILD_DIR)/lexer.o

# This is PHONY to force the Bison generated source files to re-generate
# between debug and release builds.
src/bison/parser.cc: src/bison/swarm.yy
	$(EPARSER) $<
	$(Q)cd src/bison && $(BISON) -v -Wall --defines=grammar.hh -v swarm.yy -o parser.cc

$(DEBUG_BUILD_DIR)/parser.o: src/bison/parser.cc
	$(ECXX) $<
	$(Q)$(CXX) $(CPPFLAGS_debug) -c -o $@ $<

src/bison/parser_debug.cc: src/bison/swarm.yy
	$(EPARSER) $<
	$(Q)cd src/bison && $(BISON) -v -Wall --defines=grammar.hh -v swarm.yy -o parser_debug.cc

$(DEBUG_BUILD_DIR)/parser_debug.o: src/bison/parser_debug.cc
	$(ECXX) $<
	$(Q)$(CXX) $(CPPFLAGS_debug) -c -o $@ $<


.PHONY: clean
clean:
	$(Q)$(RM) -r $(BUILD_DIR) $(TARGET_EXEC) $(DEBUG_BUILD_DIR) $(TARGET_EXEC)_debug $(BISON_FILES) run_tests vgcore.*


.PHONY: test
test: $(TARGET_EXEC)
	./bin/run_tests.bash

-include $(DEPS)

MKDIR_P ?= mkdir -p

.PHONY: docker
docker: Dockerfile
	docker image build -t "${DOCKER_REGISTRY}/swarmlang/swarm:latest" .

.PHONY: docker_run
docker_run:
	docker run --rm -it "${DOCKER_REGISTRY}/swarmlang/swarm:latest" bash

.PHONY: binn
binn:
	git submodule update --init
	$(MAKE) -C mod/binn
	sudo $(MAKE) -C mod/binn install
