<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array>
    <string>swarm</string>
   </array>
  <key>name</key>
  <string>swarm</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.swarm</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\-\-\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.swarm</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.swarm</string>
          <key>end</key>
          <string>(\*\-\-)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.swarm</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\-\-[^\*].*)</string>
          <key>name</key>
          <string>comment.swarm</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(numberToString|booleanToString|vectorToString|matrixToString|sin|cos|tan|random|randomVector|randomMatrix|zeroVector|zeroMatrix|range|lLog|sLog|lError|sError|floor|ceiling|max|min|nthRoot|count|time|subVector|subMatrix|tag|open|read|write|append)</string>
          <key>name</key>
          <string>entity.name.function.swarm</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(enumerate|with|while|if|as|include|from|shared|constructor)</string>
          <key>name</key>
          <string>keyword.swarm</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(number|bool|map|string|enumerable|fn|type)</string>
          <key>name</key>
          <string>entity.name.type.swarm</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b[a-zA-Z_][a-zA-Z0-9_]*)</string>
          <key>name</key>
          <string>variable.swarm</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\d+\.\d+)</string>
          <key>name</key>
          <string>constant.numeric.swarm</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.swarm</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swarm</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swarm</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(;|\.|\^|,|&lt;|&gt;|=|\[|\]|\+|-|\*|\/|\!|:|&amp;|\||%)</string>
          <key>name</key>
          <string>punctuation.swarm</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.swarm</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.swarm</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.swarm</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swarm</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.swarm</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.swarm</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
